title: Antonio Di Lauro
name: Antonio Di Lauro
email: antonio02120212@gmail.com
description: MSc in Information Engineering @ UniTrento — Software Engineering, ML, Distributed Systems, HPC.

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# già ok
url: "https://antodila.github.io"
baseurl: ""

collections:
  projects:
    output: true
  pages:
    output: true

# (facoltativo ma utile)
include:
  - _pages

# Stile e breadcrumb del tema
minimal_mistakes_skin: default
breadcrumbs: true

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      classes: wide
      toc: false
      share: false

