title: Antonio Di Lauro
name: Antonio Di Lauro
email: antonio02120212@gmail.com
description: MSc student in Information Engineering @ University of Trento. Software Engineering, Machine Learning, Distributed Systems, HPC.
# URL del sito (lascia vuoto finché non usi custom domain)
url: "https://antodila.github.io"
baseurl: ""
github_username: antodila
linkedin_username: antonio-di-lauro-b22905298

# Disattiva voci che non ti servono ora
google_scholar: false
orcid_username: 
twitter_username:

# Impostazioni estetiche minime (puoi personalizzare in seguito)
theme_skin: default
markdown: kramdown
highlighter: rouge
