title: Antonio Di Lauro
name: Antonio Di Lauro
email: antonio02120212@gmail.com
description: MSc in Information Engineering @ UniTrento — Software Engineering, ML, Distributed Systems, HPC.

url: "https://antodila.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

author:
  name: "Antonio Di Lauro"
  avatar: "assets/images/AntoIm_v2.jpg"
  bio: "MSc in Information Engineering @ UniTrento. Interests: Software Engineering, ML, Distributed Systems, HPC."
  location: "Trento, Italy"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/antodila"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/antonio-di-lauro-b22905298"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:antonio02120212@gmail.com"


plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

collections:
  projects:
    output: true
  pages:
    output: true

include:
  - _pages
