title: Antonio Di Lauro
name: Antonio Di Lauro
email: antonio02120212@gmail.com
description: MSc in Information Engineering @ UniTrento — Software Engineering, ML, Distributed Systems, HPC.

url: "https://antodila.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

author: "Antonio Di Lauro"   # ← aggiungi questa riga

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

collections:
  projects:
    output: true
  pages:
    output: true

include:
  - _pages
