title: Antonio Di Lauro
name: Antonio Di Lauro
email: antonio02120212@gmail.com
description: MSc in Information Engineering @ UniTrento — Software Engineering, ML, Distributed Systems, HPC.

url: "https://antodila.github.io"
baseurl: ""   # importante: vuoto per il sito utente

# Abilita le collezioni che vuoi usare
collections:
  projects:
    output: true
  pages:
    output: true

# (opzionale) plugin supportati da GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
